import 'fake-indexeddb/auto';
import JSZip from 'jszip';
import ExcelJS from 'exceljs';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { createProject, deleteProject } from '../db/repositories/projects';
import { setCourseSchedule, updateCalendarDay } from '../db/repositories/calendar';
import { createTask } from '../db/repositories/tasks';
import { confirmScheduleDraft, createRescheduleDraft, createScheduleDraft } from '../db/repositories/plans';
import { recordActual } from '../db/repositories/actual';
import { createExam, uploadExamFile } from '../db/repositories/exams';
import { exportProjectBackup, prepareProjectBackup, restoreProjectBackup } from '../db/repositories/backup';
import { buildWorkPlanView } from '../core/excel/planView';
import { buildWorkPlanXlsx } from '../core/excel/workbook';
import { buildExamPackage } from '../core/files/examPackage';
import { readProjectDashboard } from '../db/repositories/dashboard';
import { CurriculumDatabase } from '../db/schema';

let database: CurriculumDatabase;
beforeEach(() => { database = new CurriculumDatabase(`acceptance-${crypto.randomUUID()}`); });
afterEach(async () => { await database.delete(); });

describe('V1 physics workflow', () => {
  it('runs from semester setup through schedule, Excel, deviation, exam ZIP and full restore', async () => {
    const project = await createProject({ schoolYear: '2026-2027', grade: '九年级', subject: '物理', semester: '第一学期', startDate: '2026-09-01', endDate: '2027-01-23' }, database);
    await setCourseSchedule(project.id, 2, [1], database);
    await setCourseSchedule(project.id, 4, [2], database);
    await updateCalendarDay(project.id, '2026-10-01', { dayType: 'holiday', title: '国庆节' }, database);
    await createTask(project.id, { title: '13.1-13.2', type: 'new_lesson', plannedPeriods: 2, allowSplit: true }, database);
    await createTask(project.id, { title: '13.3', type: 'new_lesson', plannedPeriods: 1, allowSplit: true }, database);
    const v1 = await confirmScheduleDraft(project.id, await createScheduleDraft(project.id, database), '开学初计划', database);
    const days = await database.calendarDays.where('projectId').equals(project.id).toArray();
    const lessons = await database.scheduledLessons.where('planVersionId').equals(v1.id).toArray();
    const rows = buildWorkPlanView({ project, calendarDays: days, lessons, weeklyNotes: [], annotations: [], specialDuties: [], exams: [] });
    expect(rows).toHaveLength(24);
    const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.load(Buffer.from(await (await buildWorkPlanXlsx(project, rows, days)).arrayBuffer()) as unknown as Parameters<typeof workbook.xlsx.load>[0]);
    expect(workbook.getWorksheet('备课组工作计划')?.getCell('J2').value).toContain('13.1-13.2');
    await recordActual(lessons.find(row => row.taskPeriodIndex === 1)!.id, { status: 'completed', actualPeriods: 1 }, database);
    await recordActual(lessons.find(row => row.taskPeriodIndex === 2)!.id, { status: 'postponed', reason: '临时停课' }, database);
    const draft = await createRescheduleDraft(project.id, database);
    expect(draft.result.lessons[0].date).toBe(v1.scheduleSnapshot[0].date);
    const v2 = await confirmScheduleDraft(project.id, draft, '延期后顺延', database);
    expect(v2.version).toBe(2);
    const exam = await createExam(project.id, { title: '13-14章检测', examType: 'chapter_test', examDate: '2026-10-15', authorNames: ['甲老师'], reviewerNames: ['乙老师'] }, database);
    const paper = await uploadExamFile(exam.id, 'paper_pdf', new Blob(['sample-paper-pdf'], { type: 'application/pdf' }), '原始试卷.pdf', database);
    const answer = await uploadExamFile(exam.id, 'answer_pdf', new Blob(['sample-answer-pdf'], { type: 'application/pdf' }), '原始答案.pdf', database);
    const payloads = await Promise.all([paper, answer].map(async metadata => ({ metadata, blob: (await database.fileBlobs.get(metadata.blobId))!.blob })));
    const examZip = await buildExamPackage(project, exam, payloads);
    const archive = await JSZip.loadAsync(await examZip.blob.arrayBuffer());
    expect(Object.keys(archive.files).filter(path => path.endsWith('.pdf'))).toHaveLength(2);
    const dashboard = (await readProjectDashboard(project.id, '2026-09-20', database))!;
    expect(dashboard.completed).toBe(1);
    expect(dashboard.nextExam?.id).toBe(exam.id);
    expect(dashboard.attachmentBytes).toBe(new Blob(['sample-paper-pdf']).size + new Blob(['sample-answer-pdf']).size);
    const backup = await exportProjectBackup(project.id, database);
    const prepared = await prepareProjectBackup(backup.blob);
    await deleteProject(project.id, database);
    expect(await database.exams.where('projectId').equals(project.id).count()).toBe(0);
    expect(await database.scheduledLessons.where('projectId').equals(project.id).count()).toBe(0);
    expect(await database.fileBlobs.count()).toBe(0);
    const restored = await restoreProjectBackup(prepared, database);
    expect(await database.teachingTasks.where('projectId').equals(restored.id).count()).toBe(2);
    expect(await database.planVersions.where('projectId').equals(restored.id).count()).toBe(2);
    expect(await database.actualRecords.where('projectId').equals(restored.id).count()).toBe(2);
    expect(await database.exams.where('projectId').equals(restored.id).count()).toBe(1);
    const restoredFiles = await database.examFiles.where('projectId').equals(restored.id).toArray();
    expect((await Promise.all(restoredFiles.map(async metadata => (await database.fileBlobs.get(metadata.blobId))!.blob.text()))).sort()).toEqual(['sample-answer-pdf', 'sample-paper-pdf']);
  });
});
